import type { WeatherZone, DisruptionZone, ZoomPreset, VesselState } from './types';

export const MARITIME_WEATHER_ZONES: WeatherZone[] = [
  {
    id: 'wz-arabian-storm',
    name: 'Arabian Sea Monsoon Storm Cell',
    lat: 14.5,
    lng: 63.8,
    radius_km: 450,
    condition: 'storm',
    severity: 'critical',
    wind_speed_kmh: 78,
    wind_gust_kmh: 104,
    temperature_c: 28.5,
    speed_reduction_pct: 35,
    estimated_delay_hours: 24,
    wave_height_m: 6.2,
    description: 'Severe cyclonic storm system causing severe sea swells and navigation rerouting.',
  },
  {
    id: 'wz-bay-bengal-rain',
    name: 'Bay of Bengal Depressions',
    lat: 11.2,
    lng: 85.6,
    radius_km: 380,
    condition: 'rain',
    severity: 'high',
    wind_speed_kmh: 52,
    wind_gust_kmh: 68,
    temperature_c: 27.2,
    speed_reduction_pct: 18,
    estimated_delay_hours: 12,
    wave_height_m: 3.8,
    description: 'Heavy precipitation corridor with moderate surface chop and reduced visibility.',
  },
  {
    id: 'wz-english-channel-fog',
    name: 'English Channel Maritime Fog Zone',
    lat: 50.1,
    lng: -0.8,
    radius_km: 220,
    condition: 'fog',
    severity: 'moderate',
    wind_speed_kmh: 14,
    wind_gust_kmh: 22,
    temperature_c: 13.0,
    speed_reduction_pct: 15,
    estimated_delay_hours: 6,
    wave_height_m: 1.2,
    description: 'Dense sea fog reducing optical visibility below 500m; vessels operating on fog radar protocols.',
  },
  {
    id: 'wz-south-china-clear',
    name: 'South China Sea Corridor',
    lat: 16.8,
    lng: 114.2,
    radius_km: 500,
    condition: 'clear',
    severity: 'normal',
    wind_speed_kmh: 18,
    wind_gust_kmh: 25,
    temperature_c: 30.1,
    speed_reduction_pct: 0,
    estimated_delay_hours: 0,
    wave_height_m: 1.0,
    description: 'Calm waters and optimal visibility along standard eastbound sea lane.',
  },
  {
    id: 'wz-mediterranean-calm',
    name: 'Eastern Mediterranean Passage',
    lat: 34.2,
    lng: 26.5,
    radius_km: 360,
    condition: 'clear',
    severity: 'normal',
    wind_speed_kmh: 22,
    wind_gust_kmh: 30,
    temperature_c: 24.5,
    speed_reduction_pct: 0,
    estimated_delay_hours: 0,
    wave_height_m: 1.4,
    description: 'Normal sea state with clear horizon and favorable tailwinds.',
  },
  {
    id: 'wz-malacca-rain',
    name: 'Strait of Malacca Monsoon Front',
    lat: 2.8,
    lng: 101.4,
    radius_km: 260,
    condition: 'rain',
    severity: 'moderate',
    wind_speed_kmh: 38,
    wind_gust_kmh: 48,
    temperature_c: 29.0,
    speed_reduction_pct: 10,
    estimated_delay_hours: 4,
    wave_height_m: 2.1,
    description: 'Scattered squalls and localized rain bands across active transit lane.',
  },
];

export const MARITIME_DISRUPTIONS: DisruptionZone[] = [
  {
    id: 'DIS-ROTTERDAM',
    name: 'Port of Rotterdam Strike',
    location: 'Rotterdam, NL',
    lat: 51.9244,
    lng: 4.4777,
    radius_km: 180,
    type: 'port_strike',
    severity: 'high',
    affected_count: 93,
    impact_summary: 'Automated container terminals halted due to dock union collective action.',
    delay_days: 5,
    active: true,
  },
  {
    id: 'DIS-SUEZ',
    name: 'Suez Canal Restriction',
    location: 'Suez Canal, EG',
    lat: 30.5852,
    lng: 32.2654,
    radius_km: 160,
    type: 'canal_restriction',
    severity: 'critical',
    affected_count: 42,
    impact_summary: 'Southbound convoy throughput throttled due to channel maintenance & security protocols.',
    delay_days: 4,
    active: true,
  },
  {
    id: 'DIS-SINGAPORE',
    name: 'Singapore Port Berth Congestion',
    location: 'Singapore, SG',
    lat: 1.29027,
    lng: 103.851959,
    radius_km: 140,
    type: 'port_strike',
    severity: 'medium',
    affected_count: 58,
    impact_summary: 'Anchorage turnaround times extended by 36-48 hours amid peak transshipment volume.',
    delay_days: 2,
    active: true,
  },
  {
    id: 'DIS-RED-SEA',
    name: 'Bab-el-Mandeb Geopolitical Security Zone',
    location: 'Bab-el-Mandeb Strait',
    lat: 12.5833,
    lng: 43.3333,
    radius_km: 280,
    type: 'geopolitical_crisis',
    severity: 'critical',
    affected_count: 65,
    impact_summary: 'Heightened maritime security advisory; mandatory convoy escorts or Cape reroutes.',
    delay_days: 7,
    active: true,
  },
];

export const ZOOM_LEVEL_MAP: Record<ZoomPreset, number> = {
  60: 3,   // Global fleet overview
  80: 4,   // Regional network
  100: 5,  // Shipment routes & transit hubs
  120: 7,  // Selected shipment corridor
  150: 9,  // Detailed vessel & berth approach
};

export const RISK_COLOR_HEX: Record<string, string> = {
  normal: '#10B981',   // Green
  low: '#10B981',      // Green
  moderate: '#F59E0B', // Yellow / Amber
  medium: '#F59E0B',   // Yellow / Amber
  high: '#F97316',     // Orange
  critical: '#EF4444', // Red
};

export const DEFAULT_FLEET_VESSELS: VesselState[] = [
  {
    shipment_id: 'SHP-1042',
    origin: 'Shanghai, CN',
    destination: 'Rotterdam, NL',
    carrier: 'Maersk',
    cargo_type: 'vaccine',
    status: 'in_transit',
    value_usd: 280000,
    latitude: 14.82,
    longitude: 64.18,
    current_speed_knots: 14.2,
    normal_speed_knots: 19.5,
    progress_percent: 68,
    distance_travelled_km: 8420,
    distance_remaining_km: 3960,
    current_leg: 'Singapore → Suez Canal',
    route_waypoints: ['Shanghai', 'Singapore', 'Suez Canal', 'Rotterdam'],
    eta: 'Sep 21, 2026',
    risk: 'critical',
  },
  {
    shipment_id: 'SHP-1087',
    origin: 'Shenzhen, CN',
    destination: 'Rotterdam, NL',
    carrier: 'Evergreen',
    cargo_type: 'electronics',
    status: 'delayed',
    value_usd: 420000,
    latitude: 9.54,
    longitude: 88.32,
    current_speed_knots: 16.5,
    normal_speed_knots: 20.0,
    progress_percent: 54,
    distance_travelled_km: 6710,
    distance_remaining_km: 5720,
    current_leg: 'Shenzhen → Singapore',
    route_waypoints: ['Shenzhen', 'Singapore', 'Suez Canal', 'Rotterdam'],
    eta: 'Sep 23, 2026',
    risk: 'high',
  },
  {
    shipment_id: 'SHP-1155',
    origin: 'Jeddah, SA',
    destination: 'Rotterdam, NL',
    carrier: 'CMA CGM',
    cargo_type: 'frozen_goods',
    status: 'in_transit',
    value_usd: 310000,
    latitude: 15.22,
    longitude: 41.80,
    current_speed_knots: 12.0,
    normal_speed_knots: 18.0,
    progress_percent: 42,
    distance_travelled_km: 2150,
    distance_remaining_km: 2970,
    current_leg: 'Jeddah → Suez Canal',
    route_waypoints: ['Jeddah', 'Suez Canal', 'Rotterdam'],
    eta: 'Sep 20, 2026',
    risk: 'critical',
  },
  {
    shipment_id: 'SHP-1188',
    origin: 'Shanghai, CN',
    destination: 'Los Angeles, US',
    carrier: 'Yang Ming',
    cargo_type: 'electronics',
    status: 'in_transit',
    value_usd: 520000,
    latitude: 28.50,
    longitude: -155.20,
    current_speed_knots: 19.8,
    normal_speed_knots: 21.0,
    progress_percent: 75,
    distance_travelled_km: 7850,
    distance_remaining_km: 2620,
    current_leg: 'Singapore → Los Angeles',
    route_waypoints: ['Shanghai', 'Singapore', 'Pacific Ocean', 'Los Angeles'],
    eta: 'Sep 18, 2026',
    risk: 'medium',
  },
  {
    shipment_id: 'SHP-1201',
    origin: 'Mumbai, IN',
    destination: 'Hamburg, DE',
    carrier: 'ONE',
    cargo_type: 'electronics',
    status: 'in_transit',
    value_usd: 380000,
    latitude: 12.91,
    longitude: 43.62,
    current_speed_knots: 11.5,
    normal_speed_knots: 20.5,
    progress_percent: 61,
    distance_travelled_km: 5120,
    distance_remaining_km: 3280,
    current_leg: 'Mumbai → Suez Canal',
    route_waypoints: ['Mumbai', 'Suez Canal', 'Hamburg'],
    eta: 'Sep 25, 2026',
    risk: 'high',
  },
  {
    shipment_id: 'SHP-1103',
    origin: 'Mumbai, IN',
    destination: 'Rotterdam, NL',
    carrier: 'MSC',
    cargo_type: 'standard',
    status: 'in_transit',
    value_usd: 95000,
    latitude: 34.52,
    longitude: 24.12,
    current_speed_knots: 18.0,
    normal_speed_knots: 18.5,
    progress_percent: 82,
    distance_travelled_km: 7420,
    distance_remaining_km: 1630,
    current_leg: 'Suez Canal → Rotterdam',
    route_waypoints: ['Mumbai', 'Suez Canal', 'Rotterdam'],
    eta: 'Sep 17, 2026',
    risk: 'low',
  },
  {
    shipment_id: 'SHP-1145',
    origin: 'Tokyo, JP',
    destination: 'Los Angeles, US',
    carrier: 'ONE',
    cargo_type: 'electronics',
    status: 'in_transit',
    value_usd: 670000,
    latitude: 35.12,
    longitude: -142.40,
    current_speed_knots: 15.2,
    normal_speed_knots: 21.0,
    progress_percent: 66,
    distance_travelled_km: 5890,
    distance_remaining_km: 3030,
    current_leg: 'Tokyo → Los Angeles',
    route_waypoints: ['Tokyo', 'Pacific Ocean', 'Los Angeles'],
    eta: 'Sep 22, 2026',
    risk: 'high',
  },
  {
    shipment_id: 'SHP-1118',
    origin: 'Hamburg, DE',
    destination: 'Rotterdam, NL',
    carrier: 'Hapag-Lloyd',
    cargo_type: 'perishable',
    status: 'in_transit',
    value_usd: 175000,
    latitude: 53.40,
    longitude: 5.12,
    current_speed_knots: 13.8,
    normal_speed_knots: 17.5,
    progress_percent: 91,
    distance_travelled_km: 410,
    distance_remaining_km: 40,
    current_leg: 'Hamburg → Rotterdam',
    route_waypoints: ['Hamburg', 'Rotterdam'],
    eta: 'Sep 15, 2026',
    risk: 'critical',
  },
];

